# Generated by Django 4.2.29 on 2026-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Уникальный идентификатор записи во внешней системе', max_length=255, unique=True, verbose_name='External ID')),
                ('user_id', models.PositiveBigIntegerField(help_text='Идентификатор пользователя', verbose_name='User ID')),
                ('email', models.EmailField(help_text='Email получателя', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(help_text='Тема письма', max_length=255, verbose_name='Subject')),
                ('message', models.TextField(help_text='Текст письма', verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mailings',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='mailings_status_b9b966_idx'), models.Index(fields=['created_at'], name='mailings_created_48c0fb_idx')],
            },
        ),
    ]
